// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ManageFarm.Models;

public partial class FarmDatabaseContext : DbContext
{
    public FarmDatabaseContext(DbContextOptions<FarmDatabaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Field> Fields { get; set; }

    public virtual DbSet<Machine> Machines { get; set; }

    public virtual DbSet<Staff> Staff { get; set; }

    public virtual DbSet<Task> Tasks { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Field>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Field__3214EC0700A8E46B");

            entity.ToTable("Field");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Crop)
                .HasMaxLength(45)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<Machine>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Machine__3214EC07FBCF565C");

            entity.ToTable("Machine");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.FieldId).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.NextTestDate)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("date");
            entity.Property(e => e.Status)
                .HasMaxLength(45)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Type)
                .HasMaxLength(45)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.Field).WithMany(p => p.Machines)
                .HasForeignKey(d => d.FieldId)
                .HasConstraintName("Machine_Field_Id");
        });

        modelBuilder.Entity<Staff>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Staff__3214EC07F67B145D");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ContactInfo)
                .HasMaxLength(45)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)");
            entity.Property(e => e.HourlyWage)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Name)
                .HasMaxLength(45)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Role)
                .HasMaxLength(45)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<Task>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Task__3214EC07166E2760");

            entity.ToTable("Task");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Description)
                .HasMaxLength(45)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)");
            entity.Property(e => e.FieldId).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.MachineId).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.StaffId).HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.Field).WithMany(p => p.Tasks)
                .HasForeignKey(d => d.FieldId)
                .HasConstraintName("Task_Field_Id");

            entity.HasOne(d => d.Machine).WithMany(p => p.Tasks)
                .HasForeignKey(d => d.MachineId)
                .HasConstraintName("Task_Machine_Id");

            entity.HasOne(d => d.Staff).WithMany(p => p.Tasks)
                .HasForeignKey(d => d.StaffId)
                .HasConstraintName("Task_Staff_Id");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}