// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ManageFarm.Models;

public partial class Field
{
    public int Id { get; set; }

    public string Crop { get; set; }

    public virtual ICollection<Machine> Machines { get; set; } = new List<Machine>();

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}