// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ManageFarm.Models;

public partial class Machine
{
    public int Id { get; set; }

    public string Type { get; set; }

    public DateTime? NextTestDate { get; set; }

    public string Status { get; set; }

    public int? FieldId { get; set; }

    public virtual Field Field { get; set; }

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}