// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ManageFarm.Models;

public partial class Staff
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string ContactInfo { get; set; }

    public decimal? HourlyWage { get; set; }

    public string Role { get; set; }

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}