// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ManageFarm.Models;

public partial class Task
{
    public int Id { get; set; }

    public string Description { get; set; }

    public int? FieldId { get; set; }

    public int? MachineId { get; set; }

    public int? StaffId { get; set; }

    public virtual Field Field { get; set; }

    public virtual Machine Machine { get; set; }

    public virtual Staff Staff { get; set; }
}